---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: vcenter.example.com
      username: administrator@vsphere.local
      password: 1234Qwer@
      validate_certs: False
      name: deneme02
      template: template
      datacenter: Datacenter
      folder: /Datacenter/vm/sunucu
      state: poweredon
      wait_for_ip_address: yes
